name 'robquistnl-puppet-zimbra'
version '0.0.1'

author 'Rob Quist'
license 'Apache2'
project_page 'http://www.github.com/RobQuistNL/puppet-zimbra'
source 'https://github.com/RobQuistNL/puppet-zimbra'
summary 'Puppet module for Zimbra mailserver'
description 'This module installs and manages Zimbra mailserver. Check README for details.'
dependency 'example42/puppi', '>=2.0.0'
dependency 'example42/firewall', '>=2.0.0'
dependency 'example42/monitor', '>=2.0.0'
